stages: # 分段
  - install
  - build
  - deploy


  
cache: # 缓存
  paths:
    - _build

install-job:
  tags:
    - pdf
  stage: install
  script:
    #删除以前的缓存文件
    - make clean
    #rst转latex文件
    #- sphinx-build -b latex -D language=en -d _build/doctrees . _build/latex
    - make latex

build-job:
  tags:
    - pdf
  stage: build
  script:
  #复制相关资源文件
    - cp -r latexfile/*  _build/latex/  
  #使用python脚本处理latex文件
    - python3 latexbuild.py
  #latex文件生成pdf
    - cd _build/latex/ && latexmk -r latexmkrc -pdf -f -dvi- -ps-  -interaction=nonstopmode
  
  #允许错误运行
  #allow_failure: true


PDF-files:
  tags:
    - pdf
  stage: deploy
  script:
    #修改文件名称
    - python3 latexbuild2.py 
    #移动文件到指定位置 
    - cp _build/latex/*.pdf ./
    #网盘同步，在不同的仓库中都需要修改
    #F103拂晓
    - find /home/flyleaf/ebf_nas/公司共享/百度云对外发布资料/STM32产品线/STM32电机系列/野火【F103开发板-拂晓】光盘资料/A盘（资料盘）/1-程序源码_教程文档/6-[野火]《电机应用开发实战指南—基于STM32》/ -name "*.pdf" | xargs rm
    - cp _build/latex/*.pdf /home/flyleaf/ebf_nas/公司共享/百度云对外发布资料/STM32产品线/STM32电机系列/野火【F103开发板-拂晓】光盘资料/A盘（资料盘）/1-程序源码_教程文档/6-[野火]《电机应用开发实战指南—基于STM32》/
    #F407骄阳
    - find /home/flyleaf/ebf_nas/公司共享/百度云对外发布资料/STM32产品线/STM32电机系列/野火【F407开发板-骄阳】光盘资料/A盘（资料盘）/1-程序源码_教程文档/8-[野火]《电机应用开发实战指南—基于STM32》/ -name "*.pdf" | xargs rm
    - cp _build/latex/*.pdf /home/flyleaf/ebf_nas/公司共享/百度云对外发布资料/STM32产品线/STM32电机系列/野火【F407开发板-骄阳】光盘资料/A盘（资料盘）/1-程序源码_教程文档/8-[野火]《电机应用开发实战指南—基于STM32》//
    #H743繁星
    - find /home/flyleaf/ebf_nas/公司共享/百度云对外发布资料/STM32产品线/STM32电机系列/野火【H743开发板-繁星】光盘资料/A盘（资料盘）/1-程序源码_教程文档/8-[野火]《电机应用开发实战指南—基于STM32》/ -name "*.pdf" | xargs rm
    - cp _build/latex/*.pdf /home/flyleaf/ebf_nas/公司共享/百度云对外发布资料/STM32产品线/STM32电机系列/野火【H743开发板-繁星】光盘资料/A盘（资料盘）/1-程序源码_教程文档/8-[野火]《电机应用开发实战指南—基于STM32》/

  artifacts:
    name: 'PDFfile' #下载压缩包文件名
    paths: #文件路径
      - ./*.pdf
    expire_in: 1 day #保存时间
    when: on_success #仅在job成功后上传
